eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
logging:
    level:
        com.github.hollykunge.servicewebservice.dao: debug
mybatis:
    mapper-locations: classpath:mapper/*.xml
    typeAliasesPackag: com.github.hollykunge.servicewebservice.model
server:
    port: 8090
spring:
    application:
        name: service-webservice
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@//10.11.24.136:1521/arltr
        username: lark_admin
        password: 123456
    jpa:
        database: oracle
        hibernate:
            ddl-auto: update
    rabbitmq:
        host: ${RABBIT_MQ_HOST:10.11.24.135}
        port: ${RABBIT_MQ_PORT:5672}
        listener:
            simple:
                acknowledge-mode: manual
                retry:
                    enabled: true
                    initial-interval: 3000ms
                    max-attempts: 8
        username: hollykunge
        password: 123456
        publisher-confirms: true
        publisher-returns: true
        virtual-host: /
    userreadxmladdress: C:\userxml\userreadxml
    userxmladdress: C:\userxml
    address: http://10.11.1.29/axis/services/BizService
    cronb: 0 0 * * * ?
